apiVersion: v1
kind: Service
metadata:
  name: tapservice
  namespace: tap
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: deploytap
  type: ClusterIP